# Generated by Django 2.2.1 on 2020-03-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200315_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
